### ISSUE TITLE
Example Request - RTOS with Zephyr or FreeRTOS

### ISSUE THREAD

**Issue by rolandhordos** [madmachineio/Examples#3]
Hi, I'd love to see an RTOS example using Swift and Zephyr or FreeRTOS.  Perhaps with [this as the model](https://create.arduino.cc/projecthub/feilipu/using-freertos-multi-tasking-in-arduino-ebc3cc)?

**Comment by andy0808** [comment]
> Hi, I'd love to see an RTOS example using Swift and Zephyr or FreeRTOS. Perhaps with [this as the model](https://create.arduino.cc/projecthub/feilipu/using-freertos-multi-tasking-in-arduino-ebc3cc)?

Hi @rolandhordos , sorry for this late reply! Almost all the SwiftIO API is based on Zephyr. We have written a middle layer to hide the complexity of the Zeypher RTOS, you could find the headers [here](https://github.com/madmachineio/SwiftIO/tree/main/Sources/CSwiftIO/include).

We plan to open source this middle layer later this year, at that time, then we may write some documents on how to modify the middle layer
